apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DB_NAME: mydatabase
  DJANGO_DB_USER: myuser
  DJANGO_DB_PASSWORD: mypassword
  DJANGO_DB_HOST: postgres
  DJANGO_DB_PORT: "5432"
